//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patterns.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Patterns.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        public static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pattern by.
        /// </summary>
        public static string APatternBy {
            get {
                return ResourceManager.GetString("APatternBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best unregistered.
        /// </summary>
        public static string BestUnregistered {
            get {
                return ResourceManager.GetString("BestUnregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush.
        /// </summary>
        public static string Brush {
            get {
                return ResourceManager.GetString("Brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush 1.
        /// </summary>
        public static string Brush1 {
            get {
                return ResourceManager.GetString("Brush1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush 3.
        /// </summary>
        public static string Brush3 {
            get {
                return ResourceManager.GetString("Brush3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush 5.
        /// </summary>
        public static string Brush5 {
            get {
                return ResourceManager.GetString("Brush5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush 7.
        /// </summary>
        public static string Brush7 {
            get {
                return ResourceManager.GetString("Brush7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octohorn.
        /// </summary>
        public static string Brush8 {
            get {
                return ResourceManager.GetString("Brush8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Days1 {
            get {
                return ResourceManager.GetString("Days1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days2 {
            get {
                return ResourceManager.GetString("Days2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days3 {
            get {
                return ResourceManager.GetString("Days3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days4 {
            get {
                return ResourceManager.GetString("Days4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete layers.
        /// </summary>
        public static string DeleteLayers {
            get {
                return ResourceManager.GetString("DeleteLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30pxart is an online tool for seamless patterns, knitting patterns and ornaments drawing. Also it&apos;s possible to convert your patterns to vector graphics. Draw amazing pattern, apply one of filters and share your picture!.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect.
        /// </summary>
        public static string Deselect {
            get {
                return ResourceManager.GetString("Deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafts.
        /// </summary>
        public static string Drafts {
            get {
                return ResourceManager.GetString("Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw patterns online.
        /// </summary>
        public static string DrawPatternsOnline {
            get {
                return ResourceManager.GetString("DrawPatternsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw your own pattern!.
        /// </summary>
        public static string DrawYourPattern {
            get {
                return ResourceManager.GetString("DrawYourPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embroidery.
        /// </summary>
        public static string Embroidery {
            get {
                return ResourceManager.GetString("Embroidery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embroidery texture.
        /// </summary>
        public static string EmbroideryTexture {
            get {
                return ResourceManager.GetString("EmbroideryTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase.
        /// </summary>
        public static string Erase {
            get {
                return ResourceManager.GetString("Erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eraser.
        /// </summary>
        public static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred..
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyedropper.
        /// </summary>
        public static string Eyedropper {
            get {
                return ResourceManager.GetString("Eyedropper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string Feed {
            get {
                return ResourceManager.GetString("Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hours1 {
            get {
                return ResourceManager.GetString("Hours1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours2 {
            get {
                return ResourceManager.GetString("Hours2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours3 {
            get {
                return ResourceManager.GetString("Hours3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours4 {
            get {
                return ResourceManager.GetString("Hours4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join our Vk community.
        /// </summary>
        public static string JoinCommunity {
            get {
                return ResourceManager.GetString("JoinCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30pxart, pixelart, pixel art, pixel, art, drawing, pixel drawing, online drawing, patterns drawing, patterns drawing online, ornaments drawing, make seamless pattern, make knitting pattern.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knitting.
        /// </summary>
        public static string Knitting {
            get {
                return ResourceManager.GetString("Knitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knitting texture.
        /// </summary>
        public static string KnittingTexture {
            get {
                return ResourceManager.GetString("KnittingTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin letters, digits and underscore only.
        /// </summary>
        public static string LatinLettersDigitsAndUnderscoreOnly {
            get {
                return ResourceManager.GetString("LatinLettersDigitsAndUnderscoreOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registered.
        /// </summary>
        public static string MemberAlready {
            get {
                return ResourceManager.GetString("MemberAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge layers.
        /// </summary>
        public static string MergeLayers {
            get {
                return ResourceManager.GetString("MergeLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string Minutes1 {
            get {
                return ResourceManager.GetString("Minutes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes2 {
            get {
                return ResourceManager.GetString("Minutes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes3 {
            get {
                return ResourceManager.GetString("Minutes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes4 {
            get {
                return ResourceManager.GetString("Minutes4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try out our Android &lt;a href=&quot;https://play.google.com/store/apps/details?id=dfgden.pxart.com.pxart&quot; target=&quot;_blank&quot;&gt;mobile application&lt;/a&gt;..
        /// </summary>
        public static string MobileApplication {
            get {
                return ResourceManager.GetString("MobileApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string Months4 {
            get {
                return ResourceManager.GetString("Months4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most commented.
        /// </summary>
        public static string MostCommented {
            get {
                return ResourceManager.GetString("MostCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best.
        /// </summary>
        public static string MostLiked {
            get {
                return ResourceManager.GetString("MostLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains inappropriate symbols.
        /// </summary>
        public static string NameContainsInappropriateSymbols {
            get {
                return ResourceManager.GetString("NameContainsInappropriateSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already taken.
        /// </summary>
        public static string NameIsAlreadyTaken {
            get {
                return ResourceManager.GetString("NameIsAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty.
        /// </summary>
        public static string NameIsEmpty {
            get {
                return ResourceManager.GetString("NameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new layer.
        /// </summary>
        public static string NewLayer {
            get {
                return ResourceManager.GetString("NewLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like it? Click on heart!.
        /// </summary>
        public static string NoLikes {
            get {
                return ResourceManager.GetString("NoLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string Override {
            get {
                return ResourceManager.GetString("Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found..
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel art.
        /// </summary>
        public static string PixelArt {
            get {
                return ResourceManager.GetString("PixelArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↵.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent unregistered.
        /// </summary>
        public static string RecentUnregistered {
            get {
                return ResourceManager.GetString("RecentUnregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflect horizontally.
        /// </summary>
        public static string ReflectHorizontally {
            get {
                return ResourceManager.GetString("ReflectHorizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflect vertically.
        /// </summary>
        public static string ReflectVertically {
            get {
                return ResourceManager.GetString("ReflectVertically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string SaveNew {
            get {
                return ResourceManager.GetString("SaveNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save pattern.
        /// </summary>
        public static string SavePattern {
            get {
                return ResourceManager.GetString("SavePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seamless pattern.
        /// </summary>
        public static string SeamlessPattern {
            get {
                return ResourceManager.GetString("SeamlessPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user name.
        /// </summary>
        public static string SelectUserName {
            get {
                return ResourceManager.GetString("SelectUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide grid.
        /// </summary>
        public static string ShowHideGrid {
            get {
                return ResourceManager.GetString("ShowHideGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide pixel grid.
        /// </summary>
        public static string ShowHidePixelGrid {
            get {
                return ResourceManager.GetString("ShowHidePixelGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in or sign up.
        /// </summary>
        public static string SignInOrSignUp {
            get {
                return ResourceManager.GetString("SignInOrSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Facebook.
        /// </summary>
        public static string SignInWithFacebook {
            get {
                return ResourceManager.GetString("SignInWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Instagram.
        /// </summary>
        public static string SignInWithInstagram {
            get {
                return ResourceManager.GetString("SignInWithInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Vk.
        /// </summary>
        public static string SignInWithVk {
            get {
                return ResourceManager.GetString("SignInWithVk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing.
        /// </summary>
        public static string Smoothing {
            get {
                return ResourceManager.GetString("Smoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles.
        /// </summary>
        public static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles texture.
        /// </summary>
        public static string TilesTexture {
            get {
                return ResourceManager.GetString("TilesTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To drafts.
        /// </summary>
        public static string ToDrafts {
            get {
                return ResourceManager.GetString("ToDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        public static string Unfollow {
            get {
                return ResourceManager.GetString("Unfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (vector).
        /// </summary>
        public static string Vector {
            get {
                return ResourceManager.GetString("Vector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper.
        /// </summary>
        public static string Wallpaper {
            get {
                return ResourceManager.GetString("Wallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        public static string Weeks1 {
            get {
                return ResourceManager.GetString("Weeks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string Weeks2 {
            get {
                return ResourceManager.GetString("Weeks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string Weeks3 {
            get {
                return ResourceManager.GetString("Weeks3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string Weeks4 {
            get {
                return ResourceManager.GetString("Weeks4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a comment....
        /// </summary>
        public static string WriteAComment {
            get {
                return ResourceManager.GetString("WriteAComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
